api = "0.7"

[buildpack]
  description = "A buildpack for configuring and running HTTPD for PHP apps"
  homepage = "https://github.com/paketo-buildpacks/php-httpd"
  id = "paketo-buildpacks/php-httpd"
  keywords = ["php", "httpd"]
  name = "Paketo PHP HTTPD Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php-httpd/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml", "config/httpd.conf"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
